post_install() {
    systemctl daemon-reload
    systemctl enable rdhm-agent.service
    echo ">>> Enable and start the agent with: systemctl start rdhm-agent"
}

pre_upgrade() {
    systemctl stop rdhm-agent.service || true
}

post_upgrade() {
    systemctl daemon-reload
    systemctl restart rdhm-agent.service || true
}

pre_remove() {
    systemctl stop rdhm-agent.service || true
    systemctl disable rdhm-agent.service || true
}

post_remove() {
    systemctl daemon-reload
}
